//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsClub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DClubEntities : DbContext
    {
		public DClubEntities()
			: base("name=DClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avard> Avards { get; set; }
        public virtual DbSet<Dog> Dogs { get; set; }
        public virtual DbSet<DogsForSale> DogsForSales { get; set; }
        public virtual DbSet<DogsPhoto> DogsPhotos { get; set; }
        public virtual DbSet<DogType> DogTypes { get; set; }
        public virtual DbSet<ExpositionMember> ExpositionMembers { get; set; }
        public virtual DbSet<Exposition> Expositions { get; set; }
        public virtual DbSet<ExpositionsRequest> ExpositionsRequests { get; set; }
        public virtual DbSet<ExpositionWinner> ExpositionWinners { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SalesHistory> SalesHistories { get; set; }
        public virtual DbSet<UsersRole> UsersRoles { get; set; }
        public virtual DbSet<Vaccination> Vaccinations { get; set; }
        public virtual DbSet<MedicalCare> MedicalCares { get; set; }
        public virtual DbSet<PaymentsPeriodType> PaymentsPeriodTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<News> News { get; set; }
    }
}
