//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        public Dog()
        {
            this.DogsForSales = new HashSet<DogsForSale>();
            this.DogsPhotos = new HashSet<DogsPhoto>();
            this.ExpositionMembers = new HashSet<ExpositionMember>();
            this.ExpositionsRequests = new HashSet<ExpositionsRequest>();
            this.SalesHistories = new HashSet<SalesHistory>();
            this.Vaccinations = new HashSet<Vaccination>();
            this.MedicalCares = new HashSet<MedicalCare>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Description { get; set; }
        public byte[] Avatar { get; set; }
        public int OwnerId { get; set; }
        public Nullable<bool> WasSold { get; set; }
        public Nullable<int> Sex { get; set; }
        public int IdDogType { get; set; }
        public string AvatarMimeType { get; set; }
    
        public virtual DogType DogType { get; set; }
        public virtual ICollection<DogsForSale> DogsForSales { get; set; }
        public virtual ICollection<DogsPhoto> DogsPhotos { get; set; }
        public virtual ICollection<ExpositionMember> ExpositionMembers { get; set; }
        public virtual ICollection<ExpositionsRequest> ExpositionsRequests { get; set; }
        public virtual ICollection<SalesHistory> SalesHistories { get; set; }
        public virtual ICollection<Vaccination> Vaccinations { get; set; }
        public virtual ICollection<MedicalCare> MedicalCares { get; set; }
        public virtual User User { get; set; }
    }
}
