//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogsPhoto
    {
        public int Id { get; set; }
        public byte[] PhotoData { get; set; }
        public string MimeType { get; set; }
        public int DogId { get; set; }
    
        public virtual Dog Dog { get; set; }
    }
}
