//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpositionWinner
    {
        public int Id { get; set; }
        public int IdExpositionMember { get; set; }
        public int IdAvard { get; set; }
        public int WinnerPlace { get; set; }
    
        public virtual Avard Avard { get; set; }
        public virtual ExpositionMember ExpositionMember { get; set; }
    }
}
