//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exposition
    {
        public Exposition()
        {
            this.ExpositionMembers = new HashSet<ExpositionMember>();
            this.ExpositionsRequests = new HashSet<ExpositionsRequest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateStart { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ExpositionMember> ExpositionMembers { get; set; }
        public virtual ICollection<ExpositionsRequest> ExpositionsRequests { get; set; }
    }
}
