//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpositionsRequest
    {
        public int Id { get; set; }
        public int IdExposition { get; set; }
        public int IdDog { get; set; }
    
        public virtual Dog Dog { get; set; }
        public virtual Exposition Exposition { get; set; }
    }
}
