//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public decimal PaySize { get; set; }
        public System.DateTime PayDate { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public int IdType { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual User User { get; set; }
    }
}
