//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Dogs = new HashSet<Dog>();
            this.Payments = new HashSet<Payment>();
            this.SalesHistories = new HashSet<SalesHistory>();
            this.SalesHistories1 = new HashSet<SalesHistory>();
            this.UsersRoles = new HashSet<UsersRole>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public byte[] Avatar { get; set; }
        public string AvatarMimeType { get; set; }
        public Nullable<int> Sex { get; set; }
    
        public virtual ICollection<Dog> Dogs { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<SalesHistory> SalesHistories { get; set; }
        public virtual ICollection<SalesHistory> SalesHistories1 { get; set; }
        public virtual ICollection<UsersRole> UsersRoles { get; set; }
    }
}
